#!bash

# because I often tyop `bre w...` instead of `brew ...`
bre() {
    _fix_swapped_w_and_space brew "$@"
} 

# and likewise for `perlbrew` ...
perlbre() {
    _fix_swapped_w_and_space perlbrew "$@"
} 

_fix_swapped_w_and_space() {
    local executable=$1
    shift

    local firstarg="$1"
    shift
    case $firstarg in
      w*)
        firstarg="${firstarg:1}"
        $executable "$firstarg" "$@"
        ;;
      *)
        echo $(echo -n $executable | sed 's/w$//'): No such file or directory >&2
        return 1
        ;;
    esac
}
