#!sh
tree() {
    $(which tree) $(cat ~/.treerc 2>/dev/null) "$@"    
    # if [[ "$#" == "1" && "$1" == *.local ]]; then
    #     dig "$1" @224.0.0.251 -p 5353 |grep -i "^$1"
    # else
    #     $(which host) "$@"
    # fi
} 
