#!bash

if [[ "$(which brew 2>/dev/null)" != "" ]]; then
    complete -F __brew_bash_completions brew

    # because I often tyop `bre w...` instead of `brew ...`
    complete -F __bre_w_bash_completions bre

    # regenerate this if more than a week old
    if [ ! -f ~/.brew.commands ] || [ $(find ~/.brew.commands -maxdepth 0 -mtime +7) ]; then
        brew commands -q | grep ^[[:alpha:]] > ~/.brew.commands
    fi
fi

__brew_bash_completions () {
    COMPREPLY=();
    local thisword="${COMP_WORDS[COMP_CWORD]}";

    # if there's only one word on the command line
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=($(compgen -W "$(cat ~/.brew.commands)" -- "$thisword"));
    fi
}

__bre_w_bash_completions () {
    COMPREPLY=();
    local thisword="${COMP_WORDS[COMP_CWORD]}";

    # if there's only one word on the command line
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=($(compgen -W "$(sed 's/^/w/' ~/.brew.commands)" -- "$thisword"));
    fi
}
