# format = "$all$directory$character"

add_newline = false

[directory]
truncation_length = 0
truncate_to_repo = true
truncation_symbol = " …/"

[git_branch]
format = "[on $branch ]($style)"

[custom.git_lfs]
format = "[($output )](bold purple)"
when = "[ -e .git/config ]"
command = "grep -q ^.lfs .git/config && echo git lfs"

[c]
detect_extensions = ["c", "h", "xs"]
# format = "using [$symbol($name $version )]($style)"
format = "using [$symbol]($style)"

[perl]
format = "using [$symbol ($version )]($style)"
symbol = "perl"
detect_extensions = ["pl", "pm"]

[character]
success_symbol = "[\\$](bold green)"
error_symbol   = "[\\$](bold red)"

[line_break]
disabled = true

[hostname]
format = "[$hostname]($style):"

[username]
format = "[$user]($style)@"

[cmd_duration]
disabled = true
