# format = "$all$directory$character"

add_newline = false

[directory]
truncation_length = 0
truncate_to_repo = true
truncation_symbol = " …/"

[git_branch]
format = "[on $branch ]($style)"

[c]
detect_extensions = ["c", "h", "xs"]
format = "using [$symbol($name $version )]($style)"

[perl]
format = "using [$symbol ($version )]($style)"
symbol = "perl"
detect_extensions = ["pl", "pm"]

[character]
success_symbol = "[\\$](bold green)"
error_symbol   = "[\\$](bold red)"

[line_break]
disabled = true

[cmd_duration]
disabled = true
